defaultSemverRangePrefix: ''

nmMode: hardlinks-global

plugins:
  - path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://raw.githubusercontent.com/WillBooster/yarn-plugin-auto-install/main/dist/index.cjs'

yarnPath: .yarn/releases/yarn-4.0.0-rc.5.cjs
