name: Add issue to github project

on:
  workflow_call:
    inputs:
      target_organization:
        required: false
        type: string
    secrets:
      GH_PROJECT_URL:
        required: true
      GH_BOT_PAT:
        required: true

jobs:
  add-to-project:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.GH_BOT_PAT }}
          labeled: project
