name: Add issue to github project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.GH_BOT_PAT }}
          labeled: project
