name: Add close comment

on:
  workflow_call:
    inputs:
      target_organization:
        required: false
        type: string

jobs:
  close-comment:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 3
    steps:
      - run: |
          mkdir -p temp
          echo  "const { execSync } = require('child_process');" > temp/addCloseComment.js
          echo "const headRef = '${{github.head_ref}}';" >> temp/addCloseComment.js
          echo "const prNumber = '${{ github.event.pull_request.number }}';" >> temp/addCloseComment.js
          echo "const repository = '${{ github.repository }}';" >> temp/addCloseComment.js
          cat >> temp/addCloseComment.js << EOF
          const url = \`https://github.com/\${repository}/pull/\${prNumber}\`
          const [issueNumber] = headRef.split(/[-_]/);
          const closeComment= \`close #\${issueNumber}\`;
          const closeCommentReg = new RegExp(closeComment);
          re=/^[0-9]+$/;
          if(re.test(issueNumber)){
              let newBody = "";
              const stdout = execSync(\`gh pr view \${url} --json body\`);
              let commentBody = JSON.parse(stdout)["body"];
              if(!closeCommentReg.test(commentBody)){
                  newBody=\`\${closeComment}\r\n\${commentBody}\`;
              }
              if(closeCommentReg.test(newBody)){
                  execSync(\`gh pr edit \${url} --body "\${newBody}"\`);
              }
          }
          EOF
          node temp/addCloseComment.js
          rm -Rf temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}