name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: wb-mac-1
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      - run: |
          yarn --version
          asdf shell yarn 1.22.18
          yarn --version
      - run: |
          yarn --version
          asdf shell yarn 1.22.17
          yarn --version
      - run: |
          yarn --version
          asdf shell yarn 1.22.18
          yarn --version
