name: Debug

on:
  workflow_call:

jobs:
  debug:
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -al
