name: Debug

on:
  workflow_call:

jobs:
  debug:
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "medium", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "medium", "ARM64"]')) || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -al
