name: Debug

on:
  workflow_call:

jobs:
  debug:
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 3
    steps:
      - name: Add Homebrew to PATH for Apple Silicon
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -al
