name: Debug

on:
  workflow_call:

jobs:
  debug:
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -al
