name: Deploy app

on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      deploy_command:
        required: false
        type: string
      dot_env_path:
        default: .env
        required: false
        type: string
      environment:
        required: true
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      ignore_renovate:
        required: false
        type: boolean
      runs_on:
        required: false
        type: string
      server_url:
        required: false
        type: string
      target_organization:
        required: false
        type: string
      version:
        required: false
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: false
      DOT_ENV:
        required: false
      FLY_API_TOKEN:
        required: false
      GCP_SA_KEY_JSON:
        required: false
      GCP_SA_KEY_JSON_FOR_FIREBASE:
        required: false
      GH_TOKEN:
        required: false

jobs:
  pre:
    if: ${{ (!inputs.target_organization || github.repository_owner == inputs.target_organization) && (!inputs.ignore_renovate || (github.event.head_commit.author.username != 'renovate-bot' && github.event.head_commit.author.username != 'renovate[bot]')) }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: false
          skip_after_successful_duplicate: true
          paths_ignore: '["*.md"]' # Ignore only markdown files on root
  deploy:
    needs: pre
    if: ${{ needs.pre.outputs.should_skip != 'true' }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    env:
      # constants
      GCLOUD_VERSION: 406.0.0
      PYTHON_VERSION: 3.9.15
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
      # arguments
      ENVIRONMENT: ${{ inputs.environment }}
      HAS_DISCORD_WEBHOOK_URL: ${{ !!secrets.DISCORD_WEBHOOK_URL }}
      HAS_DOT_ENV: ${{ !!secrets.DOT_ENV }}
      HAS_FLY_API_TOKEN: ${{ !!secrets.FLY_API_TOKEN }}
      HAS_GCP_SA_KEY_JSON: ${{ !!secrets.GCP_SA_KEY_JSON }}
      HAS_GCP_SA_KEY_JSON_FOR_FIREBASE: ${{ !!secrets.GCP_SA_KEY_JSON_FOR_FIREBASE }}
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - uses: actions/checkout@v3
      - if: ${{ env.HAS_DOT_ENV == 'true' }}
        run: echo '${{ secrets.DOT_ENV }}' > ${{ inputs.dot_env_path }}

      - name: Check version files
        id: check-ver
        run: |
          if [[ -f .tool-versions || -f .node-version || -f .python-version ]]; then
            echo "exist-version-files=1" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.check-ver.outputs.exist-version-files }}
        uses: willbooster/asdf-actions/install@main
      - if: ${{ !steps.check-ver.outputs.exist-version-files }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version || 18 }}
      - name: Install Node.js with asdf if it doesn't exist
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            if [[ ! $(node --version) ]]; then
              asdf plugin add nodejs || true
              asdf local nodejs system
              node --version
            fi
            if [[ ! $(yarn --version) ]]; then
              asdf plugin add yarn || true
              asdf local yarn system
              if [[ ! $(yarn --version) ]]; then
                YARN_VERSION=$(npm show yarn version)
                asdf install yarn $(YARN_VERSION)
                asdf local yarn $(YARN_VERSION)
              fi
            fi
      - if: ${{ env.HAS_GCP_SA_KEY_JSON == 'true' }}
        name: Install gcloud with asdf
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            if [[ ! -f .tool-versions ]] || [[ "$(cat .tool-versions)" != *"python"* ]]; then
              asdf plugin add python || true
              asdf install python $PYTHON_VERSION
              asdf local python $PYTHON_VERSION
            fi
            if [[ ! -f .tool-versions ]] || [[ "$(cat .tool-versions)" != *"gcloud"* ]]; then
              asdf plugin add gcloud || true
              asdf install gcloud $GCLOUD_VERSION
              asdf local gcloud $GCLOUD_VERSION
            fi
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          YARN=$(yarn -v); echo "yarn: $YARN"
          if PYTHON=$(python --version 2> /dev/null); then echo "python: $PYTHON"; fi
          if POETRY=$(poetry --version 2> /dev/null); then
            echo "poetry: $POETRY"
            poetry config virtualenvs.in-project true
          fi
          if gcloud -v &> /dev/null; then echo "gcloud: $(gcloud -v 2>&1 | head -n 1)"; fi
          if [[ "$YARN" == "1."* ]]; then
            echo "yarn-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
          fi
      - name: Set environment variables
        run: |
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV
          echo "VERSION=$(git describe --always --tags)" >> $GITHUB_ENV
      - name: Verify environment variables
        run: |
          echo ${PATH}
          echo ${VERSION}

      - if: ${{ steps.env-info.outputs.yarn-dir }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.env-info.outputs.yarn-dir }}
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - if: ${{ env.HAS_FLY_API_TOKEN == 'true' }}
        name: Install fly
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: curl -L https://fly.io/install.sh | FLYCTL_INSTALL=$HOME/.fly sh
      - if: ${{ env.HAS_GCP_SA_KEY_JSON == 'true' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - if: ${{ env.HAS_GCP_SA_KEY_JSON == 'true' }}
        name: Configure docker to use gcloud
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
      - run: yarn install

      - if: ${{ env.HAS_GCP_SA_KEY_JSON_FOR_FIREBASE == 'true' }}
        name: Create credential file for Firebase
        run: echo '${{ secrets.GCP_SA_KEY_JSON_FOR_FIREBASE }}' > $GOOGLE_APPLICATION_CREDENTIALS

      - run: if [[ "$(cat package.json)" == *'"common/ci-setup":'* ]]; then yarn run common/ci-setup; fi

      - name: Deploy
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: ${{ (env.HAS_FLY_API_TOKEN == 'true' || env.HAS_GCP_SA_KEY_JSON == 'true') && 5 || 1 }}
          command: |
            if [[ "$(cat package.json)" == *'"deploy/ci-setup":'* ]]; then yarn run deploy/ci-setup; fi
            yarn run ${{ inputs.deploy_command || 'deploy' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - if: ${{ env.HAS_DISCORD_WEBHOOK_URL == 'true' && inputs.environment != 'production' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
               --data "{
                  \"username\": \"WillBooster Bot\",
                  \"avatar_url\": \"https://avatars.githubusercontent.com/u/98675783\",
                  \"content\": \"[${{ github.event.repository.name }}](${{ github.event.repository.html_url }}) の${{inputs.environment}}環境 (${{ inputs.server_url }}) を [$(git describe --always --tags)](https://github.com/${{ github.repository }}/commits/$(git describe --always --tags)) に更新しました。\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
      - if: ${{ env.HAS_DISCORD_WEBHOOK_URL == 'true' && inputs.environment == 'production' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
               --data "{
                  \"username\": \"WillBooster Bot\",
                  \"avatar_url\": \"https://avatars.githubusercontent.com/u/98675783\",
                  \"content\": \"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n[${{ github.event.repository.name }}](${{ github.event.repository.html_url }}) の本番環境 (${{ inputs.server_url }}) を [$(git describe --always --tags)](https://github.com/${{ github.repository }}/commits/$(git describe --always --tags)) に更新しました。\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - run: docker system prune -a -f --filter "until=24h"

      - if: ${{ always() }}
        name: Delete credential files
        run: rm -f $GOOGLE_APPLICATION_CREDENTIALS ${{ inputs.dot_env_path }}
