name: Show a given text

on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      text:
        required: true
        type: string
    outputs:
      text:
        value: ${{ jobs.echo.outputs.text }}

jobs:
  echo:
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch && fromJSON(format('["self-hosted", "medium", "{0}"]', inputs.cpu_arch))) || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 1
    outputs:
      text: ${{ steps.echo.outputs.text }}
    steps:
      - uses: actions/checkout@v3
      - uses: willbooster/asdf-actions/install@main
      - id: echo
        run: |
          echo "text=${{ inputs.text }}" >> $GITHUB_OUTPUT
