name: Show a given text

on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      text:
        required: true
        type: string
    outputs:
      text:
        value: ${{ jobs.echo.outputs.text }}

jobs:
  echo:
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    outputs:
      text: ${{ steps.echo.outputs.text }}
    steps:
      - uses: actions/checkout@v3
      - uses: willbooster/asdf-actions/install@main
      - id: echo
        run: |
          echo "text=${{ inputs.text }}" >> $GITHUB_OUTPUT
