name: Release

on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      dot_env_path:
        default: .env
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      ignore_renovate:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: false
      DOT_ENV:
        required: false
      GH_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  release:
    if: ${{ (!inputs.target_organization || github.repository_owner == inputs.target_organization) && (!inputs.ignore_renovate || (github.event.head_commit.author.username != 'renovate-bot' && github.event.head_commit.author.username != 'renovate[bot]')) }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    env:
      HAS_DISCORD_WEBHOOK_URL: ${{ !!secrets.DISCORD_WEBHOOK_URL }}
      HAS_DOT_ENV: ${{ !!secrets.DOT_ENV }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ env.HAS_DOT_ENV == 'true' }}
        run: echo '${{ secrets.DOT_ENV }}' > ${{ inputs.dot_env_path }}

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      # However, we must use asdf if .tool-versions since it may install some tools other than Node.js
      - name: Get Node.js version
        id: get-ver
        run: |
          if [[ -f .tool-versions ]]; then
            echo "::set-output name=exist-tool-versions::1";
          fi
          if [[ "$(cat .tool-versions)" != *"node"* ]]; then
            echo "::set-output name=node::$(cat .node-version || echo 16)";
          fi
      - if: ${{ steps.get-ver.outputs.exist-tool-versions }}
        uses: willbooster/asdf-actions/install@main
      - if: ${{ steps.get-ver.outputs.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-ver.outputs.node }}
      - if: ${{ steps.get-ver.outputs.node }}
        name: Install Node.js with asdf
        run: |
          asdf plugin add nodejs || true
          asdf plugin add yarn || true
          asdf local nodejs system && asdf local yarn system
          if [[ ! $(yarn --version) ]]; then
            YARN_VERSION=$(npm show yarn version)
            asdf install yarn $(YARN_VERSION) && asdf local yarn $(YARN_VERSION)
          fi
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
          echo "yarn: $(yarn -v)"
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi

      - if: ${{ steps.env-info.outputs.yarn-dir }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.env-info.outputs.yarn-dir }}
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - run: yarn install
      - run: if [[ "$(cat package.json)" == *'"build":'* ]]; then yarn build; fi
      - run: |
          if [[ "$(cat package.json)" == *'"release":'* ]]; then
            yarn release
          else
            yarn semantic-release
          fi
        # Existing GITHUB_TOKEN cannot trigger release (published) event
        # We need to pass a personal token (e.g. secrets.GH_BOT_PAT) to secrets.GH_TOKEN
        # c.f. https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0

      - if: ${{ env.HAS_DISCORD_WEBHOOK_URL == 'true' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
               --data "{
                  \"username\": \"WillBooster Bot\",
                  \"avatar_url\": \"https://avatars.githubusercontent.com/u/98675783\",
                  \"content\": \"[${{ github.event.repository.name }}](${{ github.event.repository.html_url }})の最新版([$(git describe --always --tags)]((https://github.com/${{ github.repository }}/commits/${{ steps.env-info.outputs.git-revision }}))) をリリースしました。\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
