name: Lint PR title

on:
  workflow_call:
    inputs:
      target_organization:
        required: false
        type: string

jobs:
  semantic-pr:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    env:
      FORCE_COLOR: 1
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
