name: Lint PR title

on:
  workflow_call:
    inputs:
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
