name: Sync

on:
  workflow_call:
    inputs:
      sync_params_without_dest:
        required: false
        type: string
      target_organization:
        required: false
        type: string
        default: WillBooster
    secrets:
      DEST_GIT_URL:
        required: true

jobs:
  sync:
    # Make this workflow not work on other organizations for safety
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 3
    steps:
      - name: Add Homebrew to PATH for Apple Silicon
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      # Because one-way-git-sync requires full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Show environment information
        run: |
          echo "bun: $(bun -v)"
          echo "one-way-git-sync: $(bunx --bun one-way-git-sync --version)"

      - run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
      - run: |
          bunx --bun one-way-git-sync ${{ inputs.sync_params_without_dest }} \
            -d ${{ secrets.DEST_GIT_URL }}
        env:
          HUSKY: 0
