name: Sync

on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      sync_params_without_dest:
        required: false
        type: string
      target_organization:
        required: false
        type: string
        default: WillBooster
    secrets:
      DEST_GIT_URL:
        required: true

jobs:
  sync:
    # Make this workflow not work on other organizations for safety
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    env:
      FORCE_COLOR: 1
    steps:
      # Because one-way-git-sync requires full history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Show environment information
        run: |
          echo "node: $(node -v)"
          echo "one-way-git-sync: $(npx -y --package=one-way-git-sync@latest one-way-git-sync --version)"

      - run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
      - run: |
          npx -y --package=one-way-git-sync@latest one-way-git-sync \
            ${{ inputs.sync_params_without_dest }} \
            -d ${{ secrets.DEST_GIT_URL }}
        env:
          HUSKY: 0
