name: Test

on:
  workflow_call:
    inputs:
      artifact_path:
        required: false
        type: string
      cpu_arch:
        required: false
        type: string
      dot_env_path:
        default: .env
        required: false
        type: string
      environment:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      runs_on:
        required: false
        type: string
      target_organization:
        required: false
        type: string
    secrets:
      DOT_ENV:
        required: false
      GH_TOKEN:
        required: false
      NPM_TOKEN:
        required: false
jobs:
  pre:
    if: ${{ !startsWith(github.head_ref, 'refs/heads/renovate/') && github.head_ref != 'refs/heads/wbfy' && (!inputs.target_organization || github.repository_owner == inputs.target_organization) }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - run: echo "Disable fkirc/skip-duplicate-actions temporally due to 502 error"
  #      - id: skip_check
  #        uses: fkirc/skip-duplicate-actions@master
  #        with:
  #          cancel_others: false
  #          skip_after_successful_duplicate: true
  #          paths_ignore: '["**/*.md", "**/docs/**"]'
  detect-node-version-matrix:
    needs: pre
    if: ${{ needs.pre.outputs.should_skip != 'true' }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    env:
      # arguments
      ENVIRONMENT: ${{ inputs.environment }}
    outputs:
      json: ${{ steps.detect-node-version-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      # We need Node.js only if [[ "$(cat .tool-versions)" != *"node"* ]] && [[ ! -f .node-version ]]
      - id: check-node
        run: |
          if [[ "$(cat .tool-versions)" != *"node"* ]] && [[ ! -f .node-version ]] && [[ ! $(node --version) ]]; then
            echo "require-install=1" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.check-node.outputs.require-install }}
        uses: actions/setup-node@v3
      - id: detect-node-version-matrix
        # We must use actions/setup-node if no Node.js description exists in .tool-versions and no .node-version exists
        run: |
          NODE_VERSIONS=""
          if [[ "$(cat .tool-versions)" != *"node"* ]] && [[ ! -f .node-version ]]; then
            CONSTRAINT=$(node -e "console.log(((require('./package.json') || {}).engines || {}).node)")
            NODE_VERSIONS=$(npx -y semver -r "$CONSTRAINT" 14.999.999 16.999.999 18.999.999 | xargs | sed 's/ /","/g' | sed 's/\.999\.999//g')
          fi
          echo "json=[\"$NODE_VERSIONS\"]" >> $GITHUB_OUTPUT
  test:
    needs: detect-node-version-matrix
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.runs_on && fromJSON(inputs.runs_on)) || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    env:
      HAS_DOT_ENV: ${{ !!secrets.DOT_ENV }}
      IS_RENOVATE: ${{ github.event.head_commit.author.username == 'renovate-bot' || github.event.head_commit.author.username == 'renovate[bot]' }}
    strategy:
      matrix:
        # c.f. https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        node-version: ${{ fromJson(needs.detect-node-version-matrix.outputs.json) }}
    steps:
      #      - uses: fkirc/skip-duplicate-actions@v5.2.0
      #        with:
      #          cancel_others: true
      - uses: actions/checkout@v3
      - if: ${{ env.HAS_DOT_ENV == 'true' }}
        run: echo '${{ secrets.DOT_ENV }}' > ${{ inputs.dot_env_path }}

      - name: Check version files
        id: check-ver
        run: |
          if [[ -f .tool-versions || -f .node-version || -f .python-version ]]; then
            echo "exist-version-files=1" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.check-ver.outputs.exist-version-files }}
        uses: willbooster/asdf-actions/install@main
      - if: ${{ !steps.check-ver.outputs.exist-version-files }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version || 18 }}
      - name: Install Node.js with asdf if it doesn't exist
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            if [[ ! $(node --version) ]]; then
              asdf plugin add nodejs || true
              asdf local nodejs system
              node --version
            fi
            if [[ ! $(yarn --version) ]]; then
              asdf plugin add yarn || true
              asdf local yarn system
              if [[ ! $(yarn --version) ]]; then
                YARN_VERSION=$(npm show yarn version)
                asdf install yarn $(YARN_VERSION)
                asdf local yarn $(YARN_VERSION)
              fi
            fi
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          YARN=$(yarn -v); echo "yarn: $YARN"
          if PYTHON=$(python --version 2> /dev/null); then echo "python: $PYTHON"; fi
          if POETRY=$(poetry --version 2> /dev/null); then
            echo "poetry: $POETRY"
            poetry config virtualenvs.in-project true
          fi
          if gcloud -v &> /dev/null; then echo "gcloud: $(gcloud -v 2>&1 | head -n 1)"; fi
          if [[ "$YARN" == "1."* ]]; then
            echo "yarn-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
          fi

      - if: ${{ steps.env-info.outputs.yarn-dir }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.env-info.outputs.yarn-dir }}
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - run: yarn install
      - run: if [[ "$(cat package.json)" == *'"common/ci-setup":'* ]]; then yarn run common/ci-setup; fi
      - run: if [[ "$(cat package.json)" == *'"test/ci-setup":'* ]]; then yarn run test/ci-setup; fi
      - run: if [[ "$(cat package.json)" == *'"typecheck":'* ]]; then yarn typecheck; fi
      - run: if [[ "$(cat package.json)" == *'"lint":'* ]]; then yarn lint; fi
      - run: |
          if [[ "$(cat package.json)" == *'"build":'* ]]; then
            GIT_STATUS=$(git status)
            git status
            yarn build
            if [[ "$GIT_STATUS" != "$(git status)" && "$IS_RENOVATE" == "false" ]]; then
              echo "'yarn build' MUST NOT generate any changes."
              exit 1
            fi
          fi
      - run: |
          if [[ "$(cat package.json)" == *'"test/ci":'* ]]; then
            yarn run test/ci
          elif [[ "$(cat package.json)" == *'"test":'* ]]; then
            yarn test
          fi
      - run: |
          if [[ "$(cat package.json)" == *'"lint-staged":'* ]]; then
            for file in $(ls package.json packages/*/package.json); do
              sed -i -e 's/"name":/"name" :/' $file
              git add -A
            done
            yarn lint-staged --allow-empty
          fi
      - if: ${{ env.GITHUB_TOKEN != '' && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
        run: |
          if [[ "$(cat package.json)" == *'"semantic-release":'* ]]; then
            if [[ "$(cat package.json)" == *'"release-test":'* ]]; then
              yarn release-test
            else
              yarn semantic-release --dry-run
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: ${{ inputs.artifact_path }}
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ${{ inputs.artifact_path }}
      - run: docker system prune -a -f --filter "until=24h"
