name: Merge wbfy
on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  wbfy-merge:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    # github.event.repository.private is always true if job is scheduled
    runs-on: ${{ (inputs.github_hosted_runner && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - name: Decide action
        id: decide-action
        run: |
          mkdir -p temp
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs > temp/wbfy.json

          cat > temp/wbfy.js << EOF
          const actions = require('./wbfy.json');
          for (const run of actions?.workflow_runs ?? []) {
            if (run.name !== 'Test') continue;
            if (run.head_branch !== 'wbfy') continue;

            if (run.status !== 'completed') break;
            if (run.conclusion === 'success') {
            console.log('merge');
          } else if (run.conclusion === 'failure') {
            console.log('pr');
          }
            break;
          }
          EOF

          echo "::set-output name=action::$(node temp/wbfy.js)";
          rm -Rf temp

      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        uses: actions/checkout@v3
        # To trigger other workflows when running 'git push'
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        # Unset core.hooksPath to disable husky
        run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
          git config --unset core.hooksPath
          git merge origin/wbfy --squash
          if git diff-index --quiet HEAD --; then
            echo "No changes found"
          else
            git commit -m "chore: willboosterify this repo"
            git push origin ${{ github.event.repository.default_branch }}
          fi
        env:
          HUSKY: 0

      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        uses: octokit/request-action@v2.x
        id: repo
        with:
          route: GET /repos/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -X POST -d '{"head":"wbfy","base":"${{ fromJson(steps.repo.outputs.data).default_branch }}","title":"chore: willboosterify this repo"}' || true
