name: Merge wbfy
on:
  workflow_call:
    inputs:
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
jobs:
  wbfy-merge:
    if: ${{ github.event_name != 'pull_request' && (!inputs.target_organization || github.repository_owner == inputs.target_organization) }}
    runs-on: self-hosted
    env:
      FORCE_COLOR: 3
    steps:
      - name: Decide action
        id: decide-action
        run: |
          if [[ -z $(git ls-remote https://github.com/${{ github.repository }} --heads wbfy) ]]; then
            echo "There is no wbfy branch."
            exit 0
          fi

          mkdir -p temp
          gh run list -R ${{ github.repository }} -b wbfy -L 10 -w Test --json conclusion,event > temp/wbfy.json

          cat > temp/wbfy.cjs << EOF
          const results = require('./wbfy.json');
          for (const result of results ?? []) {
            const { event, conclusion } = result;
            if (event !== 'push') continue;

            if (conclusion === 'success') {
              console.log('merge');
            } else if (conclusion === 'failure') {
              console.log('pr');
            }
            break;
          }
          EOF

          echo "action=$(node temp/wbfy.cjs)" >> $GITHUB_OUTPUT
          rm -Rf temp

      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        # To trigger other workflows when running 'git push'
        name: Checkout code with git
        run: |
          rm -rf .git
          rm -rf ./*
          rm -rf .[^.]*
          git init
          git remote add origin git@github.com:${{ github.repository }}.git
          git fetch --depth 1 origin ${{ github.event.repository.default_branch }}
          git fetch origin wbfy
          git checkout ${{ github.event.repository.default_branch }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        # Unset core.hooksPath to disable husky
        run: |
          echo "Merging origin/wbfy into current branch with --squash..."
          git merge origin/wbfy --squash
          if git commit -m "chore: willboosterify this repo" --no-verify; then
            echo "Commit successful. Attempting to push to ${{ github.event.repository.default_branch }}..."
            if git push origin ${{ github.event.repository.default_branch }} --no-verify; then
              echo "Push to ${{ github.event.repository.default_branch }} succeeded. Deleting wbfy branch on remote..."
              git push origin :wbfy
            else
              echo "Push failed. Creating PR from wbfy to main..."
              gh pr create -R ${{ github.repository }} --head wbfy --base main --title "chore: willboosterify this repo" --body "" || true
              echo "Attempting to merge PR and delete wbfy branch..."
              gh pr merge -R ${{ github.repository }} wbfy --squash --delete-branch || true
            fi
          else
            echo "No changes to commit or commit failed."
          fi
        env:
          HUSKY: 0
          LEFTHOOK: 0

      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        run: |
          # Since a duplicated PR is not allowed
          gh pr create -R ${{ github.repository }} --head wbfy --base main --title "chore: willboosterify this repo" --body "" || true

      - name: Clean up
        if: always()
        run: gh auth logout -h github.com
