name: Merge wbfy branch
on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  merge-wbfy:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - name: Decide action
        id: decide-action
        run: |
          mkdir -p temp
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs > temp/wbfy.json

          cat > temp/wbfy.js << EOF
          const actions = require('./wbfy.json');
          for (const run of actions?.workflow_runs ?? []) {
            if (run.name !== 'Test') continue;
            if (run.head_branch !== 'wbfy') continue;

            if (run.status !== 'completed') break;
            if (run.conclusion === 'success') {
            console.log('merge');
          } else if (run.conclusion === 'failure') {
            console.log('pr');
          }
            break;
          }
          EOF

          echo "::set-output name=action::$(node temp/wbfy.js)";

      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        uses: actions/checkout@v3
        # To trigger other workflows when running 'git push'
        with:
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        run: |
          git merge origin/wbfy
          git push origin main --no-verify

      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -X POST -d '{"head":"wbfy","base":"main","title":"chore: willboosterify this repo"}' || true
