name: Merge wbfy
on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  wbfy-merge:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    # github.event.repository.private is always true if job is scheduled
    runs-on: ${{ (inputs.github_hosted_runner && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - name: Setup GitHub CLI
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Decide action
        id: decide-action
        run: |
          if [[ -z $(git ls-remote https://github.com/${{ github.repository }} --heads wbfy) ]]; then
            echo "There is no wbfy branch."
            exit 0
          fi

          mkdir -p temp
          gh run list -R ${{ github.repository }} -b wbfy -L 10 -w Test --json conclusion,event > temp/wbfy.json

          cat > temp/wbfy.js << EOF
          const results = require('./wbfy.json');
          for (const result of results ?? []) {
            const { event, conclusion } = result;
            if (event !== 'push') continue;

            if (conclusion === 'success') {
              console.log('merge');
            } else if (conclusion === 'failure') {
              console.log('pr');
            }
            break;
          }
          EOF

          echo "action=$(node temp/wbfy.js)" >> $GITHUB_OUTPUT
          rm -Rf temp

      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        uses: actions/checkout@v3
        # To trigger other workflows when running 'git push'
        with:
          ref: wbfy
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        uses: actions/checkout@v3
        # To trigger other workflows when running 'git push'
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        # Unset core.hooksPath to disable husky
        run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
          # Since wb-oracle-1 causes an error with exit code: 5
          git config --unset core.hooksPath || true
          git merge origin/wbfy --squash
          if git commit -m "chore: willboosterify this repo"; then
            git push origin ${{ github.event.repository.default_branch }}
          fi
          git push origin :wbfy
        env:
          HUSKY: 0

      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        run: |
          gh pr create --head wbfy --base main --title "chore: willboosterify this repo" --body ""

      - name: Clean up
        if: always()
        run: gh auth logout -h github.com
