name: Willboosterify
on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      force_github_host:
        required: false
        type: boolean
      # TODO(exkazuu): remove the following inputs
      non_self_hosted:
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
jobs:
  wbfy:
    runs-on: ${{ ((!github.event.repository.private || inputs.force_github_host) && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/checkout@v2
        # To trigger other workflows when running 'git push'
        with:
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ inputs.dot_env_path }}
        run: echo "${{ secrets.DOT_ENV }}" > ${{ inputs.dot_env_path }}

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      # However, we must use asdf if .tool-versions since it may install some tools other than Node.js
      - id: get-ver
        run: |
          if [[ -f .tool-versions ]] || [[ -f .node-version ]]; then
            echo "::set-output name=exist-version::1";
          fi
      - if: ${{ steps.get-ver.outputs.exist-version }}
        uses: willbooster/asdf-actions/install@main
      - uses: actions/setup-node@v2
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi

      - uses: actions/cache@v2
        with:
          path: .yarn
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - run: yarn dlx wbfy .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
          git checkout -B wbfy
          git add -A
          if [[ $(git commit -m "chore: wbfy this repo" --no-verify) ]]; then
            git push origin wbfy -f --no-verify
            curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -X POST -d '{"head":"wbfy","base":"main","title":"chore: wbfy this repo"}' || true
          fi
